wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1670718320.604906
    t:
      1:
      - 55
      3:
      - 14
      - 23
      4: 3.8.10
      5: 0.13.6
      8:
      - 5
